version: 2
root-markers:
  - .git/
tools:
  javascript-eslint: &javascript-eslint
    lint-command: './node_modules/.bin/eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
languages:
  javascript:
    - <<: *javascript-eslint
  typescriptreact:
    - <<: *javascript-eslint
